---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
helmCharts:
  - name: app-template
    releaseName: k8s-gateway
    namespace: networking
    repo: https://bjw-s.github.io/helm-charts/
    version: 1.3.2
    valuesFile: values.yaml
