---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./secret.sops.yaml
helmCharts:
  - name: external-dns
    releaseName: external-dns
    namespace: networking
    repo: https://kubernetes-sigs.github.io/external-dns
    version: 1.2.1
    valuesFile: values.yaml
