---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
helmCharts:
  - name: metallb
    releaseName: metallb
    namespace: networking
    repo: https://metallb.github.io/metallb
    version: 0.13.9
    valuesFile: values.yaml
